package store;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.math.BigDecimal;
import javax.swing.*;

public class Cambio extends javax.swing.JFrame {

    /**
     * Creates new form Cambio
     */
    public Cambio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Cambio");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCambio = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        campoCambio = new javax.swing.JTextField();
        btCalcular = new javax.swing.JButton();
        labelMoneda1 = new javax.swing.JLabel();
        labelMoneda2 = new javax.swing.JLabel();
        labelMoneda3 = new javax.swing.JLabel();
        labelRecibir = new javax.swing.JLabel();
        labelCambio = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        labelVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCambio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 90, 30));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotal.setText("0");
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 120, -1));

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTotal.setText("Total a pagar");
        getContentPane().add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        campoCambio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCambioActionPerformed(evt);
            }
        });
        getContentPane().add(campoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, -1));

        btCalcular.setText("calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        labelMoneda1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelMoneda1.setText("€");
        getContentPane().add(labelMoneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        labelMoneda2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelMoneda2.setText("€");
        getContentPane().add(labelMoneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        labelMoneda3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelMoneda3.setText("€");
        getContentPane().add(labelMoneda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        labelRecibir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelRecibir.setText("Recibí");
        getContentPane().add(labelRecibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        labelCambio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCambio.setText("Cambio");
        getContentPane().add(labelCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btCerrar.setBackground(new java.awt.Color(255, 255, 0));
        btCerrar.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        btCerrar.setText("Cerrar venta");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));
        getContentPane().add(labelVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
        BigDecimal pagoTotal= new BigDecimal(txtTotal.getText());
        BigDecimal recibi = new BigDecimal(campoCambio.getText());        
        BigDecimal operacion= recibi.subtract(pagoTotal);
        txtCambio.setText(operacion.toPlainString());
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        // TODO add your handling code here:
//        float recibi= Float.parseFloat(etCambio.getText());
        BigDecimal total= new BigDecimal(txtCambio.getText());
        if(total.compareTo(new BigDecimal(0))==-1){
            JOptionPane.showMessageDialog(null, "FALTA DINERO PARA COMPLETAR LA VENTA");
        }else{
            JOptionPane.showMessageDialog(null, "Venta realizada con éxito");
            Menu ventana1= new Menu();
            this.setVisible(false);
            ventana1.setVisible(true);
        }
        
 
    }//GEN-LAST:event_btCerrarActionPerformed

    private void campoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCambioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambio().setVisible(true);
            }
        });
    }
    public void Cambio(String totales){
        txtTotal.setText(totales);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btCerrar;
    private javax.swing.JTextField campoCambio;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JLabel labelMoneda1;
    private javax.swing.JLabel labelMoneda2;
    private javax.swing.JLabel labelMoneda3;
    private javax.swing.JLabel labelRecibir;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelVentana;
    private javax.swing.JLabel txtCambio;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
