package store;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setTitle("Inicio de sesión");
        this.setResizable(false);
        txtSalida.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JLabel();
        etPassword = new javax.swing.JPasswordField();
        Ingresar = new javax.swing.JButton();
        txtSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etUsuario = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsuario.setText("Ingresa tu contraseña");
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 230, 40));

        etPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etPassword.setToolTipText("");
        etPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                etPasswordFocusGained(evt);
            }
        });
        getContentPane().add(etPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 330, 40));

        Ingresar.setBackground(new java.awt.Color(255, 255, 0));
        Ingresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingresar.setText("Ingresar");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        txtSalida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSalida.setText("datos no validos");
        txtSalida.setToolTipText("");
        getContentPane().add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 330, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ingresa tu usuario");
        jLabel1.setMaximumSize(new java.awt.Dimension(228, 228));
        jLabel1.setMinimumSize(new java.awt.Dimension(228, 228));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 240, -1));

        etUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                etUsuarioFocusGained(evt);
            }
        });
        getContentPane().add(etUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 322, 330, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/login.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 804, 501));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        
        if(VerificarUsuario()==true&&VerificarContraseña() == true){
            Menu ventana2 = new Menu();
            this.setVisible(false);
            ventana2.setVisible(true);
        }else{
            txtSalida.setVisible(true);
            etPassword.setText(null);
            etUsuario.setText(null);
        }
        
    }//GEN-LAST:event_IngresarActionPerformed

    private void etUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_etUsuarioFocusGained
        // TODO add your handling code here:
        txtSalida.setVisible(false);
    }//GEN-LAST:event_etUsuarioFocusGained

    private void etPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_etPasswordFocusGained
        // TODO add your handling code here:
        txtSalida.setVisible(false);
    }//GEN-LAST:event_etPasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }
    private boolean VerificarContraseña(){
        String password = "123456";
        String ingresada = etPassword.getText();
        
        if(ingresada.equals(password)){
            return true;
        }
        else return false;   
    }
    private boolean VerificarUsuario(){
        String user = "admin";
        String ingresada = etUsuario.getText();
        
        if(ingresada.equals(user)){
            return true;
        }
        else return false;   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JPasswordField etPassword;
    private javax.swing.JPasswordField etUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtSalida;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
