package store;
import java.text.DecimalFormat;
import java.math.BigDecimal;

public class VentanaDescripcion extends javax.swing.JFrame {

    private BigDecimal descuento = new BigDecimal(1);
    
    
    /**
     * Creates new form VentanaDescripción
     */
    public VentanaDescripcion(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Detalles de venta");
        this.setResizable(false);
        DescuentoNoValido.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtArticulo1 = new javax.swing.JLabel();
        txtArticulo2 = new javax.swing.JLabel();
        txtArticulo3 = new javax.swing.JLabel();
        txtArticulo4 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JLabel();
        txtCantidad3 = new javax.swing.JLabel();
        txtCantidad4 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JLabel();
        txtPrecio3 = new javax.swing.JLabel();
        txtPrecio4 = new javax.swing.JLabel();
        txtDescuento1 = new javax.swing.JLabel();
        txtDescuento2 = new javax.swing.JLabel();
        txtDescuento3 = new javax.swing.JLabel();
        txtDescuento4 = new javax.swing.JLabel();
        txtPagar1 = new javax.swing.JLabel();
        txtPagar2 = new javax.swing.JLabel();
        txtPagar3 = new javax.swing.JLabel();
        txtPagar4 = new javax.swing.JLabel();
        btRegresar = new javax.swing.JButton();
        btPagar = new javax.swing.JButton();
        txtTotalPagar = new javax.swing.JLabel();
        campoDescuento = new javax.swing.JTextField();
        BotonDescuento = new javax.swing.JButton();
        DescuentoNoValido = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel1.setText("Detalles de la venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Artículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descuento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total a pagar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        txtArticulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo1.setText("Aceite vegetal");
        getContentPane().add(txtArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        txtArticulo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo2.setText("Leche de vaca");
        getContentPane().add(txtArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        txtArticulo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo3.setText("Atún en lata");
        getContentPane().add(txtArticulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, -1));

        txtArticulo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo4.setText("Refresco en lata");
        getContentPane().add(txtArticulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        txtCantidad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad1.setText("0");
        getContentPane().add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 50, -1));

        txtCantidad2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad2.setText("0");
        getContentPane().add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 50, -1));

        txtCantidad3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad3.setText("0");
        getContentPane().add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, -1));

        txtCantidad4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad4.setText("0");
        getContentPane().add(txtCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, -1));

        txtPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio1.setText("$0");
        getContentPane().add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, -1));

        txtPrecio2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio2.setText("$0");
        getContentPane().add(txtPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, -1));

        txtPrecio3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio3.setText("$0");
        getContentPane().add(txtPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, -1));

        txtPrecio4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio4.setText("$0");
        getContentPane().add(txtPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 60, -1));

        txtDescuento1.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento1.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento1.setText("$0");
        getContentPane().add(txtDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 70, -1));

        txtDescuento2.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento2.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento2.setText("$0");
        getContentPane().add(txtDescuento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 70, -1));

        txtDescuento3.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento3.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento3.setText("$0");
        getContentPane().add(txtDescuento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 70, -1));

        txtDescuento4.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento4.setForeground(new java.awt.Color(255, 255, 255));
        txtDescuento4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento4.setText("$0");
        getContentPane().add(txtDescuento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 70, -1));

        txtPagar1.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar1.setForeground(new java.awt.Color(255, 255, 255));
        txtPagar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar1.setText("$0");
        getContentPane().add(txtPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 80, -1));

        txtPagar2.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar2.setForeground(new java.awt.Color(255, 255, 255));
        txtPagar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar2.setText("$0");
        getContentPane().add(txtPagar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 80, -1));

        txtPagar3.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar3.setForeground(new java.awt.Color(255, 255, 255));
        txtPagar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar3.setText("$0");
        getContentPane().add(txtPagar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 80, -1));

        txtPagar4.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar4.setForeground(new java.awt.Color(255, 255, 255));
        txtPagar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar4.setText("$0");
        getContentPane().add(txtPagar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 80, -1));

        btRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 130, -1));

        btPagar.setBackground(new java.awt.Color(255, 255, 0));
        btPagar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPagar.setText("Pagar");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 450, 140, -1));

        txtTotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalPagar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalPagar.setText("$0");
        getContentPane().add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 110, -1));

        campoDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(campoDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 70, -1));

        BotonDescuento.setBackground(new java.awt.Color(255, 255, 0));
        BotonDescuento.setText("Aplicar");
        BotonDescuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDescuentoMouseClicked(evt);
            }
        });
        BotonDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        DescuentoNoValido.setText("Codigo de descuento no valido");
        DescuentoNoValido.setToolTipText("");
        getContentPane().add(DescuentoNoValido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 180, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/imagenes/ventanaPago.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        // TODO add your handling code here:
        Cambio ventana4 = new Cambio();
        
        this.setVisible(false);
        ventana4.setVisible(true);
        String totales =txtTotalPagar.getText();
        ventana4.Cambio(totales);
        ventana4.setVisible(true);
    }//GEN-LAST:event_btPagarActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        Menu ventana2 = new Menu();
        this.setVisible(false);
        ventana2.setVisible(true);
    }//GEN-LAST:event_btRegresarActionPerformed

    private void BotonDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonDescuentoActionPerformed

    private void campoDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescuentoActionPerformed

    private void BotonDescuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDescuentoMouseClicked
        // TODO add your handling code here:
       
        //DANI
        
    final String DESCUENTO_5 = "5OFF";
    final String DESCUENTO_10 = "10ALVARO";
    final String DESCUENTO_20 = "TUSABESCOMO";
        
    
                descuento = new BigDecimal(1);
                String codigoDescuento = campoDescuento.getText();
        

            
            if (codigoDescuento.equals(DESCUENTO_5)) {
                descuento = new BigDecimal (0.95);
                BotonDescuento.setEnabled(false);
                BotonDescuento.setVisible(false);
                DescuentoNoValido.setVisible(false);
                
            } else if (codigoDescuento.equals(DESCUENTO_10)) {
                descuento = new BigDecimal (0.90);
                BotonDescuento.setEnabled(false);
                BotonDescuento.setVisible(false);
                DescuentoNoValido.setVisible(false);
                
            } else if (codigoDescuento.equals(DESCUENTO_20)) { 
                descuento = new BigDecimal (0.80);
                BotonDescuento.setEnabled(false);
                BotonDescuento.setVisible(false);
                DescuentoNoValido.setVisible(false);
                
            } else {
                
                DescuentoNoValido.setVisible(true);
                
            }
    
            
            descuento = descuento.setScale(2, BigDecimal.ROUND_HALF_UP);
            
            
            
            
            BigDecimal nuevoPrecio = new BigDecimal (txtTotalPagar.getText());
            nuevoPrecio = nuevoPrecio.multiply(descuento);
            nuevoPrecio = nuevoPrecio.setScale(2, BigDecimal.ROUND_HALF_UP);
            txtTotalPagar.setText(nuevoPrecio.toPlainString());
            
            
            
            
    
    
    }//GEN-LAST:event_BotonDescuentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDescripcion().setVisible(true);
            }
        });
    }
    public void cantidades(String cantidad1, String cantidad2, String cantidad3, String cantidad4){
        DecimalFormat df = new DecimalFormat("#,##");
        //Cantidad
        txtCantidad1.setText(cantidad1);
        txtCantidad2.setText(cantidad2);
        txtCantidad3.setText(cantidad3);
        txtCantidad4.setText(cantidad4);
        
        //precios

        //precios + iva

        BigDecimal p1 = new BigDecimal(48.72);
        BigDecimal p2 = new BigDecimal(21.37);
        BigDecimal p3 = new BigDecimal(12.60);
        BigDecimal p4 = new BigDecimal(21.92);
        
//        String prec1 = df.format(p1);
//        String prec2 = df.format(p2);
//        String prec3 = df.format(p3);
//        String prec4 = df.format(p4);
        
        //DANI
        p1 = p1.setScale(2, BigDecimal.ROUND_HALF_UP);
        p2 = p2.setScale(2, BigDecimal.ROUND_HALF_UP);
        p3 = p3.setScale(2, BigDecimal.ROUND_HALF_UP);
        p4 = p4.setScale(2, BigDecimal.ROUND_HALF_UP);
        
        //DANI (ARRIBA)
        
 
        txtPrecio1.setText("$"+p1.toPlainString());
        txtPrecio2.setText("$"+p2.toPlainString());
        txtPrecio3.setText("$"+p3.toPlainString());
        txtPrecio4.setText("$"+p4.toPlainString());
        // descuentos
        BigDecimal cantidadp1 = new BigDecimal(cantidad1);
        BigDecimal cantidadp2 = new BigDecimal(cantidad2);
        BigDecimal cantidadp3 = new BigDecimal(cantidad3);
        BigDecimal cantidadp4 = new BigDecimal(cantidad4);
       
        
        //DESCUENTOS MODIFICADO
      /*  int cDescuentos;
        float aPagar1;
        float aPagar2;
        float aPagar3;
        float aPagar4;
        //desceuntos para productos del 1 al 4
        if(cantidadp1>=3){          
            if(cantidadp1==3){ 
                String descuento= df.format(p1);
                float cantidadF = Float.valueOf(cantidadp1);
                aPagar1= (cantidadF-1f)*p1;
                String total1 = df.format(aPagar1);
                txtDescuento1.setText("$"+descuento);
                txtPagar1.setText("$"+total1);

            }else{
                cDescuentos = (cantidadp1/3);
                int cantidad= cantidadp1-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p1*cDescuentos;
                aPagar1= p1*cantidadP;
                
                String descuento= df.format(desc);
                txtDescuento1.setText("$"+descuento);
                
                String total1= df.format(aPagar1);
                txtPagar1.setText("$"+total1);
                
            }
        }else{
            float cant1= Float.valueOf(cantidadp1);
            aPagar1= p1*cant1;
            String total1= String.valueOf(aPagar1);
            txtPagar1.setText("$"+total1);
        }
        if(cantidadp2>=3){          
            if(cantidadp2==3){ 
                String descuento= df.format(p2);
                float cantidadF = Float.valueOf(cantidadp2);
                aPagar2= (cantidadF-1f)*p2;
                String total2 = df.format(aPagar2);
                txtDescuento2.setText("$"+descuento);
                txtPagar2.setText("$"+total2); 
            }else{
                cDescuentos = (cantidadp2/3);
                int cantidad= cantidadp2-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p2*cDescuentos;
                aPagar2= p2*cantidadP;
                
                String descuento= df.format(desc);
                txtDescuento2.setText("$"+descuento);
                
                String total2= df.format(aPagar2);
                txtPagar2.setText("$"+total2);
                
            }
        }else{
            float cant2= Float.valueOf(cantidadp2);
            aPagar2= p2*cant2;
            String total2= String.valueOf(aPagar2);
            txtPagar2.setText("$"+total2);
        }
        if(cantidadp3>=3){          
            if(cantidadp3==3){ 
                String descuento= df.format(p3);
                float cantidadF = Float.valueOf(cantidadp3);
                aPagar3= (cantidadF-1f)*p3;
                String total3 = df.format(aPagar3);
                txtDescuento3.setText("$"+descuento);
                txtPagar3.setText("$"+total3);
            }else{
                cDescuentos = (cantidadp3/3);
                int cantidad= cantidadp3-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p3*cDescuentos;
                aPagar3= p3*cantidadP;
                
                String total3= df.format(desc);
                txtDescuento3.setText("$"+total3);
                
                String descuentoTotal= df.format(aPagar3);
                txtPagar3.setText("$"+descuentoTotal);
                
            }
        }else{
            float cant3= Float.valueOf(cantidadp3);
            aPagar3= p3*cant3;
            String total3= String.valueOf(aPagar3);
            txtPagar3.setText("$"+total3);
        }
        if(cantidadp4>=3){          
            if(cantidadp4==3){ 
                String descuento= df.format(p4);
                float cantidadF = Float.valueOf(cantidadp4);
                aPagar4= (cantidadF-1f)*p4;
                String total4 = df.format(aPagar4);
                txtDescuento4.setText("$"+descuento);
                txtPagar4.setText("$"+total4);
            }else{
                cDescuentos = (cantidadp4/3);
                int cantidad= cantidadp4-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p4*cDescuentos;
                aPagar4= p4*cantidadP;
                
                String descuento= df.format(desc);
                txtDescuento4.setText("$"+descuento);
                
                String total4= df.format(aPagar4);
                txtPagar4.setText("$"+total4);
                
            }
        }else{
            float cant4= Float.valueOf(cantidadp4);
            aPagar4= p4*cant4;
            String total4= df.format(aPagar4);
            txtPagar4.setText("$"+total4);
        }
        
        float pagoTotal= aPagar1 + aPagar2 + aPagar3 + aPagar4;
        String pagoTotalS = df.format(pagoTotal);
        txtTotalPagar.setText(pagoTotalS);
      */
      
      //Lo de ABAJO es MIO
      
      BigDecimal pagoP1 = p1.multiply(cantidadp1);
      BigDecimal pagoP2 = p2.multiply(cantidadp2);
      BigDecimal pagoP3 = p3.multiply(cantidadp3);
      BigDecimal pagoP4 = p4.multiply(cantidadp4);
      txtPagar1.setText("$"+pagoP1.toPlainString());
      txtPagar2.setText("$"+pagoP2.toPlainString());
      txtPagar3.setText("$"+pagoP3.toPlainString());
      txtPagar4.setText("$"+pagoP4.toPlainString());
      
      
 

      BigDecimal pagoTotal = p1.multiply(cantidadp1);
      pagoTotal=pagoTotal.add(p2.multiply(cantidadp2));
      pagoTotal=pagoTotal.add(p3.multiply(cantidadp3));
      pagoTotal=pagoTotal.add(p4.multiply(cantidadp4));
      
      //Dani
      
     
      //Dani arriba
      
     // float descuento = (float) 0;
     // float descuento2;
        
//        descuento2 = pagoTotal * descuento;
//        float precioConDescuento = pagoTotal - descuento2;
//        pagoTotal = precioConDescuento;
        String pagoTotalS = df.format(pagoTotal);
        txtTotalPagar.setText(pagoTotal.toPlainString());
        
        
        
        
        //Lo de ARRIBA es MIO
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDescuento;
    private javax.swing.JLabel DescuentoNoValido;
    private javax.swing.JButton btPagar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JTextField campoDescuento;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtArticulo1;
    private javax.swing.JLabel txtArticulo2;
    private javax.swing.JLabel txtArticulo3;
    private javax.swing.JLabel txtArticulo4;
    private javax.swing.JLabel txtCantidad1;
    private javax.swing.JLabel txtCantidad2;
    private javax.swing.JLabel txtCantidad3;
    private javax.swing.JLabel txtCantidad4;
    private javax.swing.JLabel txtDescuento1;
    private javax.swing.JLabel txtDescuento2;
    private javax.swing.JLabel txtDescuento3;
    private javax.swing.JLabel txtDescuento4;
    private javax.swing.JLabel txtPagar1;
    private javax.swing.JLabel txtPagar2;
    private javax.swing.JLabel txtPagar3;
    private javax.swing.JLabel txtPagar4;
    private javax.swing.JLabel txtPrecio1;
    private javax.swing.JLabel txtPrecio2;
    private javax.swing.JLabel txtPrecio3;
    private javax.swing.JLabel txtPrecio4;
    private javax.swing.JLabel txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
